package constant

const (
	ERROR_BAD_REQUEST           string = "BAD_REQUEST"
	ERROR_UNAUTHORIZED          string = "UNAUTHORIZED"
	ERROR_INTERNAL_SERVER_ERROR string = "INTERNAL_SERVER_ERROR"
	ERROR_SERVICE_UNAVAILABLE   string = "SERVICE_UNAVAILABLE"
	ERROR_ENDPOINT_NOT_FOUND    string = "ENDPOINT_NOT_FOUND"
	ERROR_METHOD_NOT_ALLOW      string = "METHOD_NOT_ALLOW"
)
